--CREATES
CREATE TABLE TRANSACTIONS (
	TRANSACTIONNAME			VARCHAR(255)	NOT NULL,
	TRANSACTIONSCATEGORY		VARCHAR(255)	NOT NULL,
	TRANSACTIONDATE			DATE		NOT NULL,
	TRANSACTIONSVALUE		DECIMAL		NOT NULL,
	TRANSACTIONSTYPE		NUMERIC(1,0)	NOT NULL,
	ID				VARCHAR(40)	NOT NULL,
	USR				VARCHAR(40)	NOT NULL
);

CREATE TABLE USR (
	EMAIL VARCHAR(40)	NOT NULL,
	PASS VARCHAR(40)	NOT NULL,
);

--PRIMARY KEYS
ALTER TABLE TRANSACTIONS ADD CONSTRAINT PK_TRANSACTIONS
    PRIMARY KEY (ID);

ALTER TABLE USR ADD CONSTRAINT PK_USR
    PRIMARY KEY (EMAIL);

--FOREIGN KEYS
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_USR
    FOREIGN KEY(USR) REFERENCES TRANSACTIONS(ID);
